services:
  # A Docker web service
  - type: web
    name: egodb
    env: docker
    repo: https://github.com/ego-io/egodb.git
    region: singapore
    plan: starter
    branch: develop
    rootDir: .
    numInstances: 1
    healthCheckPath: /health
    pullRequestPreviewsEnabled: true
    domains:
      - demo.egodb.io
