previewsEnabled: true
services:
  # A Docker web service
  - type: web
    name: undb
    env: docker
    repo: https://github.com/undb-xyz/undb.git
    region: singapore
    plan: starter
    rootDir: .
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: UNDB_ADMIN_EMAIL
        value: test@example.com
      - key: UNDB_ADMIN_PASSWORD
        value: 123456
    domains:
      - demo.undb.xyz
