previewsEnabled: true
services:
  # A Docker web service
  - type: web
    name: undb
    env: docker
    repo: https://github.com/undb-xyz/undb.git
    region: singapore
    plan: starter
    rootDir: .
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: PUBLIC_UNDB_ADMIN_EMAIL
        value: test@example.com
      - key: PUBLIC_UNDB_ADMIN_PASSWORD
        value: 123456
      - key: PUBLIC_UNDB_IS_DEMO
        value: 'true'
      - key: PUBLIC_UNDB_ANALYTICS
        value: '/stats/js/script.js'
    domains:
      - demo.undb.xyz
    routes:
      - type: rewrite
        source: /stats/js/script.js
        destination: https://plausible.io/js/script.js
      - type: rewrite
        source: /stats/api/event
        destination: https://plausible.io/api/event
