version: '3'

services:
  backend:
    platform: linux/x86_64
    container_name: egodb-backend
    restart: unless-stopped
    image: egodb/backend:main
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
    volumes:
      - ~/.ego/data/:/var/opt/.ego/data
    networks:
      - egodb

  web:
    platform: linux/x86_64
    container_name: egodb-web
    restart: unless-stopped
    depends_on:
      - backend
    image: egodb/web:main
    ports:
      - 3000:3000
    environment:
      - EGODB_API_TRPC_URL=http://backend:4000/api/trpc
    networks:
      - egodb

networks:
  egodb:
