name: CI

on:
  push:
    branches: ['release/*', 'main']

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    strategy:
      matrix:
        target: [web, backend]
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.EGODB_DOCKERHUB_USERNAME }}
          password: ${{ secrets.EGODB_DOCKERHUB_TOKEN }}
      - name: Build egodb/${{ matrix.target }} and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./docker/${{ matrix.target }}/Dockerfile
          tags: egodb/${{ matrix.target }}:latest
